CREATE DATABASE IF NOT EXISTS teo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'teo_app'@'%' IDENTIFIED BY 'BITTE_UNBEDINGT_AENDERN';
GRANT SELECT, INSERT, UPDATE, CREATE ON teo.* TO 'teo_app'@'%';
FLUSH PRIVILEGES;

USE teo;

CREATE TABLE IF NOT EXISTS teo_state (
  id TINYINT UNSIGNED NOT NULL,
  revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
  payload JSON NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_by VARCHAR(40) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT chk_teo_singleton CHECK (id = 1)
) ENGINE=InnoDB
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
